name: Lint

on: [push, pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install ruff
      run: pip install ruff
    - name: Check style
      run: ruff check --config .ruff.toml gpu4pyscf
    - name: Check NumPy
      run: ruff check --select NPY --ignore NPY002 gpu4pyscf
  flake:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install flake8
      run: pip install "flake8>=3.7.0"
    - name: Static analysis
      run: flake8 --config .flake8 gpu4pyscf
